module.exports = {
	CANVAS_WIDTH : 900,
	CANVAS_HEIGHT : 500,

	BALL_RADIUS : 10,
	BALL_SPEED : 15,
	BALL_ACCELERATION: 0.01,

	PLAYER_SIZE_X : 10,
	PLAYER_SIZE_Y : 150,
	PLAYER_SPEED_X : 15,
	PLAYER_SPEED_Y : 15,

	LEFT: 'LEFT',
	RIGHT: 'RIGHT'
}